NEWBIE_GROUP: "newbie"
discord_bot:
  token: "DISCORD_TOKEN"
  prefix: "&"
  status: "jogar.pryzat.com"
events:
  colheitamaldita:
    enabled: false
  draculaexpedition:
    enabled: false

classes:
  SWORDSMAN:
    displayName: "&f&lCavaleiro"
    material: "IRON_SWORD"
    description:
      - "Lore 1"
      - "Lore 2"
      - "Lore 3"
  MAGE:
    displayName: "&b&lMago"
    material: "STICK"
    description:
      - "Lore 1"
      - "Lore 2"
      - "Lore 3"
  ROGUE:
    displayName: "&d&lLadino"
    material: "NETHERITE_SWORD"
    description:
      - "Lore 1"
      - "Lore 2"
      - "Lore 3"
  ARCHER:
    displayName: "&a&lArqueiro"
    material: "BOW"
    description:
      - "Lore 1"
      - "Lore 2"
      - "Lore 3"
  PRIEST:
    displayName: "&e&lSacerdote"
    material: "SLIME_BALL"
    description:
      - "Lore 1"
      - "Lore 2"
      - "Lore 3"

# Configurações dos mobs ou entidades.
entity_settings:
  zombie:
    experience: 10
  slime:
    experience: 100
  pig:
    experience: 1
  cow:
    experience: 1
  wither:
    experience: 2000

pvp:
  # Nível minimo para entrar em combate
  min-level: 20
  # Diferença maxima de nível entre dois jogadores para poderem ir pvp. (Desativado por padrão, coloque -1 para desativar.)
  # Exemplo: Se max-dif é 5, logo um jogador de nível 20 não pode ir pvp com alguém de nível 25.
  max-dif: -1