name: pRPG
version: '${project.version}'
main: br.pryzat.rpg.main.RpgMain
api-version: 1.18
depend: [LuckPerms, ProtocolLib, Citizens]
authors: [ PryzDev ]
description: Acrescenta um RPG dentro do jogo
website: github.com/Pryzinho
commands:
  test:
    aliases: teste
  rpg:
   description: Gerenciador do RPG
   aliases: sistema
  #Players area
  skills:
    description: Gerencia suas skills
    aliases: habilidades
  class:
    description: Define sua classe
    aliases: classe


