name: pRPG
version: '${project.version}'
main: br.pryzat.rpg.main.RpgMain
api-version: 1.20
depend: [Vault, ProtocolLib, Citizens, nLogin] #Futuramente deixar so o vault e protocol como soft
authors: [ Pry ]
description: Adiciona a base de um RPG dentro do jogo.
website: github.com/Pryzinho
commands:
  test:
    aliases: teste
  rpg:
   description: Gerenciador do RPG.
   aliases: sistema
  #Players area
  skills:
    description: Gerencia suas skills.
    aliases: habilidades
  class:
    description: Define sua classe.
    aliases: classe
  #Events area
  colheitamaldita:
    description: Gerencia o evento Colheita Maldita.
    aliases: [ecm]



